yytypescript/book

features/enum.md
列挙型 (Enum)ページの誤字を以下の通り修正しました．
- 「先頭のメンバに初期値を宣言する」のコードのコメントの値がズレていた
- 火曜日(Tuesday)がTHEになっていた
- 「中間メンバに値を代入する」のコードのWEDのカンマが抜けていた
=> 列挙型 (Enum)ページの誤字修正

features/default-type-parameter.md
- デフォルト型パラメーターの `型パラメーターの制約と併用する` の説明文を修正
https://book.yyts.org/features/default-type-parameter#paramtnotosuru
=> デフォルト型パラメーターの説明文を修正

features/generics/default-type-parameter.md, features/generics/type-parameter-constraint.md
type parameterの訳が本書中に「型引数」「型パラメーター」の2種類があったので、どちらかに統一することにした。
TypeScript Deep Dive日本語版にはtype parameterの訳語がなく参考にならなかった。
どちらが広く受入られているか、Twitterでアンケートを取った。結果は、「型引数」が62%で過半数だったため「型引数」を採用した。
=> type parameterの翻訳を「型引数」に統一する

docs/tips/generates-type-from-object-key.md
typo( `kyeof` )を発見したので修正しました。
ご確認よろしくお願いします。
=> kyeof => keyof に修正

docs/writing/markdown.md, docusaurus.config.js, tsconfig.twoslash.json
- デフォルトコンパイラオプションtsconfig.twoslash.jsonになります。
- デフォルトで`types: ["node"]`が有効になりました。`require`がサンプルコードで使えます。
=> twoslashのデフォルトコンパイラオプションを変更しました。

.husky/pre-commit, package.json, yarn.lock
close #177 
- husky, lint-staged  をパッケージとして追加
- pre-commit フックを設定してコミット時に自動整形とリンターを自動実行
#160 でも挙がっているように、textlint は偶に意図しない修正をする事がある。
コミットフックに textlint の自動修正を含めると、気づかずにテキストが意図しない形で修正される危険があるので、自動実行からは除外する。
-  自動整形: markdownlint --fix, prettier --write
- リンター: markdownlint, textlint
- 自動整形: prettier --write
=> コミット時に自動整形とリンターを自動実行する

package.json
#187 でコミット時にリントが実行される機構が追加されましたが、git hookへの登録が手動だったため、これを自動化するようにしました。
このPRよりも以前から開発環境を持っている方は、一度手動でgit hookへの登録が必要です。これを行うには`yarn`を実行してください。`yarn`の実行結果に「Git hooks installed」が表示されれば成功です。
=> feat: 🎸 huskyのgit hookがyarn install時に有効化するようになりました。

.vscode/settings.json, docs/reference/tsconfig/strictfunctiontypes.md
docs: ✏️ 「strictFunctionTypes」がメソッド型に効かないことを追記しました。
docs: ✏️ 「strictFunctionTypes」を推敲しました。
docs: ✏️ 「strictFunctionTypes」を双変の観点から説明するように変更しました。
=> docs: ✏️ 「strictFunctionTypes」双変の観点から説明するように変更、メソッド型に効かないことを追記しました。

docs/reference/functions/function-type-declaration.md
以前行ったページ分割の影響で、他のページのサンプルコードなどを覚えておかないと読めない内容になっていました。
=> docs: ✏️ 「関数の型の宣言」を単独の記事として読めるように編集しました。

docs/symbols-and-keywords.md
論理積の説明をより正確にし、それに合わせ例も追加修正しました。
truthyという言葉を使うかは迷いましたが、ページの別の箇所で使用していたため一旦ヨシとしました。
=> 「記号とキーワード」の`&&`論理積の説明と例を修正

docs/reference/functions/destructuring-assignment-parameters.md
記載されている関数の実行結果が間違っているように思います。
ドキュメントの関数定義と呼び出しは以下ですが、
```js
function foo({ a, b } = {a: 0, b: 0}) {
console.log(a, b);
}
foo();
foo({ a: 1 });
function bar([a, b] = [0, 0]) {
console.log(a, b);
}
bar();
bar([1]);
```
実行結果は手元では以下のようになりました。
```bash
$ node test.js
0 0
1 undefined
0 0
1 undefined
```
コード的にも 0 0 が正しいかと思います。
=> 誤字「@log: 1 2」を「@log: 0 0」に修正しました。

.gitignore, .yarn/.gitattributes, .yarnrc.yml, package.json
CorepackやデフォルトでYarn v3系を使っている開発者への配慮です。
CorepackやYarn v2以降を使っている場合、自動的に1.22.17が起動するようになります。
=> chore: 🤖 Yarnのバージョン指定を1.22.17に明確化しました。

docs/tips/shallow-copy-object.md
MapやSetを浅いコピー(シャローコピー)するTipsとして、`new Map(...map)`のようなスプレッド演算子を使い、Iterableを経由する方法が紹介されていました。これよりも`new Map(map)`のほうが簡潔であり、実践でもこの書き方を使うほうが良いと考えられるため、スプレッド演算子によるMap、Setのコピーの説明はコンストラクタを用いる方法に置き換えました。
Closes: #307
=> docs: 📚 Map、Setの浅いコピーはコンストラクタを使う説明を変更しました。

docs/reference/values-types-variables/object/destructuring-assignment-from-objects.md
これまで「オブジェクトの分割代入」は他のページの内容の続きとして書かれていましたが、ページの前後関係変更の影響で話の流れがなくなっていました。この変更ではその問題を解決しました。
Closes: #349
=> docs: 📚 「オブジェクトの分割代入」のページが単体で読める内容になりました。

docs/tutorials/react-like-button-tutorial.md
=> docs: 📚 誤植:「「TypeScriptはいいぞ」`に`書いてみましょう」→「「TypeScriptはいいぞ」`に書き換えて`みましょう。」

docs/tutorials/eslint.md
https://github.com/yytypescript/book/issues/424#issuecomment-1179590154 の対応として、
バージョン指定付きで yarn add している箇所は全てクォート付きで表記するように修正しました。
=> docs: zsh EXTENDED_GLOBオプションを想定してクォートを追記

docs/reference/tsconfig/nofallthroughcasesinswitch.md
=> docs: 📚 誤植:「`switch`でにおける」→「`switch`における」

docs/reference/functions/arrow-functions.md
=> docs: 📚 誤りの訂正: 簡潔文体で型が書けないは間違いでした。

docs/reference/object-oriented/interface/interface-vs-type-alias.md
`interfaceでの宣言と、type aliasによる宣言の違い`の`同名のものを宣言`セクションを書きました。
=> interfaceでの宣言と、type aliasによる宣言の違いの同名定義セクション

docs/reference/functions/function-expression.md, prh/yytypescript.yml
=> docs: 📚 誤植「再起」→「再帰」

docs/reference/functions/arrow-functions.md
コードに合わせて「hello関数」→「increment関数」へ修正しました。
=> docs: twoslashのtitleをコードの関数名に合わせるように修正

docs/overview/ecosystem.md
以下を修正します。
修正前)ブラウザ関連のJavaScript仕様を定めるがWHATWGです。
修正後)ブラウザ関連のJavaScript仕様を定めるのがWHATWGです。
=> 誤植「定めるが」→「定める`の`が」

docs/reference/type-reuse/indexed-access-types.md, docs/reference/values-types-variables/type-assertion-as.md
表記揺れがあったため、一般的な方に修正しました。
ブランケットだと毛布などを連想してしまう気がします。
=> 誤植「ブラ`ン`ケット」→「ブラケット」

docs/tips/receive-an-object-return-an-object.md
初期値を使う例なのでオプションに変更しました。
関連ページ：https://typescriptbook.jp/tips/receive-an-object-return-an-object
=> docs: isRetiredプロパティをオプションに変更

docs/reference/generics/default-type-parameter.md
デフォルト型引数を指定する方法が示されていなかったので、コードで例示しました。
検討いただけると幸いです。
関連ページ: https://typescriptbook.jp/reference/generics/default-type-parameter
=> docs: デフォルト型引数を指定するコードを追加

docs/reference/type-reuse/utility-types/omit.md
「これに気づかずに小文字で書いてしまった」の「`Omit`の結果は`createdAt`と`updatedAt`を含んでしまいます」に対する関係は逆接ではなく原因となるため、「しまっても」から「しまったため」に修正しました。
=> docs: 日本語の意味合いの違い

docs/tutorials/react-like-button-tutorial.md
- JSXのセルフクロージング要素について記述を追加
- docs: 📚 self-closingが「HTMLにはできない」を削除しました。
- feat: 🎸 文の濃度を上げました。
- feat: 🎸 JSXのシンタクス仕様書へのリンクを除きました。
- feat: 🎸 「自己閉じ要素」「自己完結型要素」と呼ばれることもある旨を追記しました。
close #363 #557
=> JSXのセルフクロージング要素について記述を追加 

docs/reference/type-reuse/mapped-types.md
=> docs: 📚 「Mapped typeではsymbolを使えない」という誤った解説を削除しました。

docs/reference/statements/control-flow-analysis-and-type-guard.md
”この名称は英語としても長いらしく”と記述があるのに
肝心の英語の名称が表記されておらず気になってしまったため
”user-defined type guard”を補足として追記します
”user defined”か"user-defined"か迷いましたが以下を参照して後者を採用しました
https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates
> To define a user-defined type guard, we simply need to define a function whose return type is a type predicate:
=> docs: "user-defined type guard"の英語表記を補足として追加

docs/reference/type-reuse/typeof-type-operator.md
=> docs: 📚 誤植:「typeof演算子」→「typeof`型`演算子」

docs/reference/type-reuse/indexed-access-types.md
=> docs: インデックスアクセス型で配列について説明している部分がタプル型だったのを修正しました。

docs/reference/object-oriented/interface/interface-vs-type-alias.md
細かい点で恐縮ですが、
「interfaceとtypeの違い」ページの最初のサンプルコードにおいて、ページのタイトルや文章構成及び後続の例に合わせて、上からinterface→typeと並ぶように修正しました
=> docs: サンプルコードの並び順を文章構成に合わせる

docs/writing/japanese-english-table.md
Fixes #664
Fixes #618 
確認用URL: https://book-git-fork-hayashi-ay-fix-664-yytypescript.vercel.app/writing/japanese-english-table
=> 「日英対訳表」に対訳を追加

docs/reference/builtin-api/date.md
- docs: 誤植「日付の`念`」→「日付の`年数`」
- docs: 誤植「`謝って`〜を使用しない」→「`誤って`〜を使用しない」
Close #669
Close #685
=> 誤植「日付の`念`」→「日付の`年数`」「`謝って`〜を使用しない」→「`誤って`〜を使用しない」

.github/PULL_REQUEST_TEMPLATE.md, .markdownlintignore
チケット駆動で関連するISSUEの関連付けやり忘れる事を防止する目的で、PRテンプレートに `close #<ISSUE番号>` を追加
close #626
=> PRのテンプレートにチケットのクローズを追加

docs/reference/values-types-variables/typeof-operator.md
https://github.com/yytypescript/book/blob/bc6273bfe3dd48e59fb4bff25261fbb6d34b53d7/docs/reference/values-types-variables/typeof-operator.md?plain=1#L22
表題の通りですが、swi`ct`h → swi`tc`h へ修正しました。
close #692
=> 誤植訂正 swicth → switch

docs/tutorials/component-test.md, docs/tutorials/react-like-button-tutorial.md
- docs: ✏️ 「いいねボタンを作ろう」をReact 18に対応しました。
- 「コンポーネントテストの「ボタンをクリックするとON/OFFの表示が切り替わる」がtesting-library/user-event@14でFAILになる問題を解決しました。 #689
close #689
close #709
=> 「コンポーネントテストの「ボタンをクリックするとON/OFFの表示が切り替わる」がtesting-library/user-event@14でFAILになる問題を解決しました。

docs/reference/statements/control-flow-analysis-and-type-guard.md
=> 誤植「早期リ`ータ`ン」→「早期リ`ター`ン」

docs/reference/type-reuse/indexed-access-types.md
=> 「インデックスアクセス型」にて配列型とタプル型を分けて解説するように変更しました。

docs/reference/builtin-api/map.md, docs/reference/values-types-variables/equality.md
close #817
noErrorがあると後続のlogがズレることが分かったので、noErrorをシンタックスの末尾に移動
ズレる原因は分かっていません
=> fix:@noErrorによる@log位置ズレの修正

docs/README.md
=> feat: 🎸 トップにAwaitedの説明を追加

docs/reference/type-reuse/mapped-types.md, docs/reference/type-reuse/utility-types/record.md
Record<string, T>や{ [K in string]: T }のような型で、存在しないキーにアクセスした場合の挙動について、読者がより深く理解できるよう解説を修正しました。
主な変更点:
- `noUncheckedIndexedAccess: false`のとき、存在しないキーへのアクセスが実行時エラーにつながる過程をコードで明示
- `noUncheckedIndexedAccess: true`を有効にすると、型が `T | undefined` となりコンパイル時に問題を検知できることを明確化
- `Record`において、キーがリテラル型の場合は上記の問題が発生しない理由を、サンプルコードを交えて詳しく解説
close #1007
=> RecordとMapped Typesのインデックスアクセスの解説を改善しました。
